# This is a basic workflow to help you get started with Actions

name: onpush

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            # Runs a set of commands using the runners shell
            - name: Run the script
              env:
                  DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
                  TELETOKEN: ${{ secrets.TELETOKEN }}
              run: |
                  python dailyclaim.py
                  echo done running daily
